// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hatuzsfdilbwijxvypcw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhdHV6c2ZkaWxid2lqeHZ5cGN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0OTg1MDgsImV4cCI6MjA3MDA3NDUwOH0.amYkKwcP36Ato_UXeCzZn_eqa9USvqurj1qImEIhR3I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});